#!/bin/bash

if [ ${DIB_DEBUG_TRACE:-0} -gt 0 ]; then
    set -x
fi
set -eu
set -o pipefail

# Set cloud-init to allow password authentication
if [ -n "${DIB_CLOUD_INIT_ALLOW_ROOT_LOGIN:-}" ]; then
    if [ -f "/etc/cloud/cloud.cfg" ]; then
        if [ -z "$(grep disable_root /etc/cloud/cloud.cfg)" ]; then
            echo "disable_root not exist. append to EOF"
            echo "disable_root: 0" >> /etc/cloud/cloud.cfg
        else
            echo "disable_root exist. make sure disable_root disable"
            sed -i -e 's/disable_root: *1/disable_root: 0/g' /etc/cloud/cloud.cfg
            sed -i -e 's/disable_root: *True/disable_root: False/g' /etc/cloud/cloud.cfg
            sed -i -e 's/disable_root: *true/disable_root: false/g' /etc/cloud/cloud.cfg
        fi
    fi
fi
